/**
 * @file Automatically generated by barrelsby.
 */

export * from './adminify-outlet-route-provider';
export * from './adminify-router-config';
export * from './adminify-router-module';
export * from './components/adminify-empty-outlet-component';
export * from './data/data-provider';
export * from './data/route-data-snapshot';
export * from './data/route-params-snapshot';
export * from './directives/adminify-outlet';
export * from './providers/providers';
export * from './providers/data-providers';
export * from './providers/params-providers';
export * from './services/adminify-outlet-route-injector-factory';
export * from './services/adminify-router-config-loader-factory';
export * from './services/adminify-router-config-loader';
export * from './services/adminify-router-preloader';
export * from './services/adminify-router';
export * from './services/router-config-loader-factory';
export * from './services/router-config-loader';
